using gpos.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace gpos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260717110000_AddAuditableProductSaleVoid")]
    public partial class AddAuditableProductSaleVoid : Migration
    {
        protected override void Up(MigrationBuilder m)
        {
            m.CreateTable(name:"sale_voids", columns:t=> new {
                id=t.Column<int>(nullable:false).Annotation("MySql:ValueGenerationStrategy", Microsoft.EntityFrameworkCore.Metadata.MySqlValueGenerationStrategy.IdentityColumn), sale_id=t.Column<int>(), branch_id=t.Column<int>(), original_daily_cash_id=t.Column<int>(nullable:true), daily_cash_id=t.Column<int>(), requested_by_user_id=t.Column<int>(), reason_code=t.Column<string>(maxLength:50,nullable:true), reason=t.Column<string>(maxLength:500), original_receipt_no=t.Column<string>(maxLength:100), original_business_date=t.Column<DateTime>(nullable:true), void_business_date=t.Column<DateTime>(), original_gross_total=t.Column<decimal>(type:"decimal(18,2)"), original_discount_amount=t.Column<decimal>(type:"decimal(18,2)"), original_rebate_amount=t.Column<decimal>(type:"decimal(18,2)"), original_vat_type=t.Column<string>(maxLength:50,nullable:true), original_vat_rate=t.Column<decimal>(type:"decimal(18,4)",nullable:true), original_taxable_amount=t.Column<decimal>(type:"decimal(18,2)"), original_vat_amount=t.Column<decimal>(type:"decimal(18,2)"), reversed_vat_amount=t.Column<decimal>(type:"decimal(18,2)"), original_net_total=t.Column<decimal>(type:"decimal(18,2)"), original_applied_payment_amount=t.Column<decimal>(type:"decimal(18,2)"), status=t.Column<string>(maxLength:30), created_at=t.Column<DateTime>(), completed_at=t.Column<DateTime>(nullable:true)
            }, constraints:c => { c.PrimaryKey("PK_sale_voids",x=>x.id); c.ForeignKey("FK_sale_voids_sales_sale_id",x=>x.sale_id,"sales","id",onDelete:ReferentialAction.Restrict); c.ForeignKey("FK_sale_voids_branches_branch_id",x=>x.branch_id,"branches","id",onDelete:ReferentialAction.Restrict); c.ForeignKey("FK_sale_voids_daily_cash_original",x=>x.original_daily_cash_id,"daily_cash","id",onDelete:ReferentialAction.Restrict); c.ForeignKey("FK_sale_voids_daily_cash_current",x=>x.daily_cash_id,"daily_cash","id",onDelete:ReferentialAction.Restrict); c.ForeignKey("FK_sale_voids_users_requested",x=>x.requested_by_user_id,"users","id",onDelete:ReferentialAction.Restrict); });
            m.CreateIndex("IX_sale_voids_sale_id","sale_voids","sale_id",unique:true); m.CreateIndex("IX_sale_voids_branch_id","sale_voids","branch_id"); m.CreateIndex("IX_sale_voids_original_daily_cash_id","sale_voids","original_daily_cash_id"); m.CreateIndex("IX_sale_voids_daily_cash_id","sale_voids","daily_cash_id"); m.CreateIndex("IX_sale_voids_requested_by_user_id","sale_voids","requested_by_user_id");
            m.CreateTable(name:"sale_void_product_items", columns:t=> new { id=t.Column<int>(nullable:false).Annotation("MySql:ValueGenerationStrategy",Microsoft.EntityFrameworkCore.Metadata.MySqlValueGenerationStrategy.IdentityColumn), sale_void_id=t.Column<int>(), product_sale_id=t.Column<int>(), product_id=t.Column<int>(), display_stock_id=t.Column<int>(), batch_id=t.Column<int>(), quantity_restored=t.Column<decimal>(type:"decimal(18,2)"), unit_cost_snapshot=t.Column<decimal>(type:"decimal(18,2)"), unit_price_snapshot=t.Column<decimal>(type:"decimal(18,2)"), restored_value=t.Column<decimal>(type:"decimal(18,2)"), before_quantity=t.Column<decimal>(type:"decimal(18,2)"), after_quantity=t.Column<decimal>(type:"decimal(18,2)"), stock_movement_id=t.Column<int>(nullable:true), created_at=t.Column<DateTime>() }, constraints:c=>{ c.PrimaryKey("PK_sale_void_product_items",x=>x.id); c.ForeignKey("FK_svpi_void",x=>x.sale_void_id,"sale_voids","id",onDelete:ReferentialAction.Restrict); c.ForeignKey("FK_svpi_product_sale",x=>x.product_sale_id,"product_sales","id",onDelete:ReferentialAction.Restrict); c.ForeignKey("FK_svpi_product",x=>x.product_id,"products","id",onDelete:ReferentialAction.Restrict); c.ForeignKey("FK_svpi_stock",x=>x.display_stock_id,"display_stocks","id",onDelete:ReferentialAction.Restrict); c.ForeignKey("FK_svpi_batch",x=>x.batch_id,"product_batches","id",onDelete:ReferentialAction.Restrict); c.ForeignKey("FK_svpi_movement",x=>x.stock_movement_id,"stock_movements","id",onDelete:ReferentialAction.Restrict); });
            m.CreateIndex("IX_svpi_void","sale_void_product_items","sale_void_id"); m.CreateIndex("IX_svpi_product_sale","sale_void_product_items","product_sale_id",unique:true); m.CreateIndex("IX_svpi_movement","sale_void_product_items","stock_movement_id",unique:true);
            m.CreateTable(name:"sale_void_payments", columns:t=>new{id=t.Column<int>(nullable:false).Annotation("MySql:ValueGenerationStrategy",Microsoft.EntityFrameworkCore.Metadata.MySqlValueGenerationStrategy.IdentityColumn),sale_void_id=t.Column<int>(),payment_id=t.Column<int>(),payment_type=t.Column<string>(maxLength:50),original_applied_amount=t.Column<decimal>(type:"decimal(18,2)"),reversed_amount=t.Column<decimal>(type:"decimal(18,2)"),tendered_amount_snapshot=t.Column<decimal>(type:"decimal(18,2)",nullable:true),change_amount_snapshot=t.Column<decimal>(type:"decimal(18,2)",nullable:true),reference_no_snapshot=t.Column<string>(maxLength:100,nullable:true),external_refund_status=t.Column<string>(maxLength:30),created_by_user_id=t.Column<int>(),created_at=t.Column<DateTime>()},constraints:c=>{c.PrimaryKey("PK_sale_void_payments",x=>x.id);c.ForeignKey("FK_svp_void",x=>x.sale_void_id,"sale_voids","id",onDelete:ReferentialAction.Restrict);c.ForeignKey("FK_svp_payment",x=>x.payment_id,"payments","id",onDelete:ReferentialAction.Restrict);c.ForeignKey("FK_svp_user",x=>x.created_by_user_id,"users","id",onDelete:ReferentialAction.Restrict);});
            m.CreateIndex("IX_svp_void","sale_void_payments","sale_void_id");m.CreateIndex("IX_svp_payment","sale_void_payments","payment_id",unique:true);m.CreateIndex("IX_svp_user","sale_void_payments","created_by_user_id");
            m.CreateTable(name:"sale_void_cash_adjustments", columns:t=>new{id=t.Column<int>(nullable:false).Annotation("MySql:ValueGenerationStrategy",Microsoft.EntityFrameworkCore.Metadata.MySqlValueGenerationStrategy.IdentityColumn),sale_void_id=t.Column<int>(),sale_id=t.Column<int>(),daily_cash_id=t.Column<int>(),branch_id=t.Column<int>(),user_id=t.Column<int>(),business_date=t.Column<DateTime>(),amount=t.Column<decimal>(type:"decimal(18,2)"),reason=t.Column<string>(maxLength:500),created_at=t.Column<DateTime>()},constraints:c=>{c.PrimaryKey("PK_sale_void_cash_adjustments",x=>x.id);c.ForeignKey("FK_svca_void",x=>x.sale_void_id,"sale_voids","id",onDelete:ReferentialAction.Restrict);c.ForeignKey("FK_svca_sale",x=>x.sale_id,"sales","id",onDelete:ReferentialAction.Restrict);c.ForeignKey("FK_svca_cash",x=>x.daily_cash_id,"daily_cash","id",onDelete:ReferentialAction.Restrict);c.ForeignKey("FK_svca_branch",x=>x.branch_id,"branches","id",onDelete:ReferentialAction.Restrict);c.ForeignKey("FK_svca_user",x=>x.user_id,"users","id",onDelete:ReferentialAction.Restrict);});
            m.CreateIndex("IX_svca_void","sale_void_cash_adjustments","sale_void_id",unique:true);m.CreateIndex("IX_svca_cash","sale_void_cash_adjustments","daily_cash_id");
            m.CreateTable(name:"voucher_redemption_reversals", columns:t=>new{id=t.Column<int>(nullable:false).Annotation("MySql:ValueGenerationStrategy",Microsoft.EntityFrameworkCore.Metadata.MySqlValueGenerationStrategy.IdentityColumn),sale_void_id=t.Column<int>(),voucher_redemption_id=t.Column<int>(),voucher_id=t.Column<int>(nullable:true),member_id=t.Column<int>(nullable:true),voucher_code_snapshot=t.Column<string>(maxLength:100,nullable:true),applied_discount_amount=t.Column<decimal>(type:"decimal(18,2)"),created_by_user_id=t.Column<int>(),created_at=t.Column<DateTime>(),reason=t.Column<string>(maxLength:500)},constraints:c=>{c.PrimaryKey("PK_voucher_redemption_reversals",x=>x.id);c.ForeignKey("FK_vrr_void",x=>x.sale_void_id,"sale_voids","id",onDelete:ReferentialAction.Restrict);c.ForeignKey("FK_vrr_redemption",x=>x.voucher_redemption_id,"voucher_redemptions","id",onDelete:ReferentialAction.Restrict);c.ForeignKey("FK_vrr_voucher",x=>x.voucher_id,"vouchers","id",onDelete:ReferentialAction.Restrict);c.ForeignKey("FK_vrr_member",x=>x.member_id,"members","id",onDelete:ReferentialAction.Restrict);c.ForeignKey("FK_vrr_user",x=>x.created_by_user_id,"users","id",onDelete:ReferentialAction.Restrict);});
            m.CreateIndex("IX_vrr_redemption","voucher_redemption_reversals","voucher_redemption_id",unique:true);m.CreateIndex("IX_vrr_void","voucher_redemption_reversals","sale_void_id");
            m.AddColumn<int>("sale_void_id","points_ledger",nullable:true);m.AddColumn<int>("reversed_points_ledger_id","points_ledger",nullable:true);m.CreateIndex("IX_points_ledger_sale_void_id","points_ledger","sale_void_id");m.CreateIndex("IX_points_ledger_reversed_points_ledger_id","points_ledger","reversed_points_ledger_id",unique:true);m.AddForeignKey("FK_points_ledger_sale_voids_sale_void_id","points_ledger","sale_void_id","sale_voids",principalColumn:"id",onDelete:ReferentialAction.Restrict);m.AddForeignKey("FK_points_ledger_points_ledger_reversed","points_ledger","reversed_points_ledger_id","points_ledger",principalColumn:"id",onDelete:ReferentialAction.Restrict);
        }
        protected override void Down(MigrationBuilder m){m.DropForeignKey("FK_points_ledger_sale_voids_sale_void_id","points_ledger");m.DropForeignKey("FK_points_ledger_points_ledger_reversed","points_ledger");m.DropIndex("IX_points_ledger_sale_void_id","points_ledger");m.DropIndex("IX_points_ledger_reversed_points_ledger_id","points_ledger");m.DropColumn("sale_void_id","points_ledger");m.DropColumn("reversed_points_ledger_id","points_ledger");m.DropTable("voucher_redemption_reversals");m.DropTable("sale_void_cash_adjustments");m.DropTable("sale_void_payments");m.DropTable("sale_void_product_items");m.DropTable("sale_voids");}
    }
}
